// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TargetCustomer___MVC.Data;

#nullable disable

namespace TargetCustomer___MVC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240514231801_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TargetCustomer___MVC.Models.AvaliacaoConsultoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultoriaID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TextoAvaliacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TextoAvaliacao");

                    b.HasKey("Id");

                    b.HasIndex("ConsultoriaID");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tabela_AvaliacaoConsultoria");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.Consultoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoConsultoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Descricao_Consultoria");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Consultoria_Ativa");

                    b.Property<string>("Representante")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_Do_Representante");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tabela_Consultorias");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CNPJ")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Email");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Senha");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("Usuario_Ativo");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_Usuario");

                    b.Property<int>("NumeroLogradouro")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Numero_Logradouro");

                    b.Property<string>("RamoDeAtuacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Ramo_De_Atuacao");

                    b.Property<string>("Razao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Razao_Social");

                    b.Property<int>("Telefone")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Tabela_Usuarios");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.AvaliacaoConsultoria", b =>
                {
                    b.HasOne("TargetCustomer___MVC.Models.Consultoria", "Consultoria")
                        .WithMany("Avalia")
                        .HasForeignKey("ConsultoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TargetCustomer___MVC.Models.Usuario", "Usuario")
                        .WithMany("Avalia")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.Consultoria", b =>
                {
                    b.HasOne("TargetCustomer___MVC.Models.Usuario", "Usuario")
                        .WithMany("Consulta")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.Consultoria", b =>
                {
                    b.Navigation("Avalia");
                });

            modelBuilder.Entity("TargetCustomer___MVC.Models.Usuario", b =>
                {
                    b.Navigation("Avalia");

                    b.Navigation("Consulta");
                });
#pragma warning restore 612, 618
        }
    }
}
